/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum QRCorrectionLevel {
  Low = 0,
  Medium = 1,
  Quartile = 2,
  High = 3
}
export interface QrCodeOptions {
  data: string
  ecc?: QRCorrectionLevel
  size?: number
}
export class QrGen {
  static toUrl(options: QrCodeOptions): Promise<string>
  static toBuff(options: QrCodeOptions): Promise<Buffer>
  static toFile(options: QrCodeOptions, path: string): Promise<void>
}
